branch-defaults:
  default:
    environment: Udagramapidev-env
    group_suffix: null
global:
  application_name: udagram-api-dev
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
